### ISSUE TITLE
local-ssh: java.jsch regex to be corrected?

### ISSUE THREAD

**Issue by felixvictor** [ties/logcheck-extrarules#3] opened 2015-02-13 08:08 UTC
I propose the following changes:
* com.jcraft.jsch.JSchException -> com\.jcraft\.jsch\.JSchException
* error: -> (error: )? as with Debian 7 the message does not contain this string

From:
```
 ^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]: error: Received disconnect from [[:alnum:].:]+: 3: com.jcraft.jsch.JSchException: Auth fail \[preauth\]$
```

to:
```
^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]:(error: )? Received disconnect from [[:alnum:].:]+: 3: com\.jcraft\.jsch\.JSchException: Auth fail \[preauth\]$
```

**Comment by ties** [comment] 2015-02-13 08:42
Thanks for the feedback :-). This regex is badly written and too permissive because of that (`.` instead of `\.`). I quickly wrote it to keep the mails caused by these scans out of my inbox and I have not looked back.

On my Debian (Wheezy/7.8/openssh-server 1:6.0p1-4+deb7u2) machine is see both types of lines:
```
Feb  6 20:13:37 antigua sshd[29759]: Received disconnect from 212.83.133.4: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]
Feb  6 20:49:38 xalias sshd[2870]: error: Received disconnect from 212.83.133.4: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]
```

I will update the regex in the way that you proposed.

**Comment by ties** [comment] 2015-02-17 21:52
Closing. Thanks for the contribution!

**Closed by ties** 2015-02-17 21:52 UTC
